services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mi_password
      MYSQL_DATABASE: mi_base_datos
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: mi_password_usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data: