CREATE SCHEMA IF NOT EXISTS youtube;
USE youtube;

CREATE TABLE IF NOT EXISTS youtube.COUNTRY(
id_country INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
CONSTRAINT pk_country PRIMARY KEY(id_country));

CREATE TABLE IF NOT EXISTS youtube.USER(
id_user INT NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
nickname VARCHAR(45) NOT NULL,
birthdate DATE NOT NULL,
gender ENUM('MASCLE', 'FEMALE', 'NOT BINARY', 'I PREFER NOT TO SAY IT'),
zip_code VARCHAR(45) NOT NULL,
id_country INT NOT NULL,
CONSTRAINT pk_user PRIMARY KEY(id_user),
CONSTRAINT fk_user_country FOREIGN KEY (id_country) REFERENCES youtube.COUNTRY(id_country)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.VIDEO(
id_video INT NOT NULL AUTO_INCREMENT,
tittle VARCHAR(45) NOT NULL,
description TEXT NOT NULL,
size DECIMAL(10,2) NOT NULL,
file_name VARCHAR(45) NOT NULL,
duration DECIMAL(4,2) NOT NULL,
thumbnail_url VARCHAR(45) NULL,
views_number INT NULL DEFAULT 0,
likes_number INT NULL DEFAULT 0,
dislikes_number INT NULL DEFAULT 0,
status ENUM('PRIVATE', 'PUBLIC','HIDDEN') NOT NULL DEFAULT 'PUBLIC',
published_at DATETIME DEFAULT CURRENT_TIMESTAMP,
id_user INT NOT NULL,
CONSTRAINT pk_video PRIMARY KEY(id_video),
CONSTRAINT fk_video_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.HASHTAG(
id_hashtag INT NOT NULL,
name VARCHAR(45) NOT NULL,
CONSTRAINT pk_hashtag PRIMARY KEY (id_hashtag));

CREATE TABLE IF NOT EXISTS youtube.VIDEO_HASHTAG(
id_video INT NOT NULL,
id_hashtag INT NOT NULL,
count INT NOT NULL,
CONSTRAINT pk_video_hashtag PRIMARY KEY(id_video, id_hashtag),
CONSTRAINT fk_video_hashtag_video FOREIGN KEY(id_video) REFERENCES youtube.VIDEO(id_video)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_video_hashtag_hashtag FOREIGN KEY(id_hashtag) REFERENCES youtube.HASHTAG(id_hashtag)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.CHANNEL(
id_channel INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
description TEXT NOT NULL,
date_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
id_user INT NOT NULL,
CONSTRAINT pk_channel PRIMARY KEY(id_channel),
CONSTRAINT fk_channel_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.SUBSCRIPTION(
id_user INT NOT NULL,
id_channel INT NOT NULL ,
date_subscription DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_subscription PRIMARY KEY(id_user, id_channel),
CONSTRAINT fk_subscription_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_subscription_channel FOREIGN KEY(id_channel) REFERENCES youtube.CHANNEL(id_channel)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.VIDEO_USER_REACTION(
id_video INT NOT NULL,
id_user INT NOT NULL,
reaction ENUM('LIKE', 'DISLIKE') NOT NULL,
reaction_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_video_user_reaction PRIMARY KEY (id_video, id_user),
CONSTRAINT fk_reaction_video FOREIGN KEY(id_video) REFERENCES youtube.VIDEO(id_video)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_reaction_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.PLAYLIST(
id_playlist INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
status ENUM('PRIVATE', 'PUBLIC','HIDDEN') NOT NULL DEFAULT 'PUBLIC',
id_user INT NOT NULL,
CONSTRAINT pk_playlist PRIMARY KEY(id_playlist),
CONSTRAINT fk_playlist_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.PLAYLIST_VIDEO(
id_playlist INT NOT NULL,
id_video INT NOT NULL,
added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_playlist_video PRIMARY KEY(id_playlist,id_video),
CONSTRAINT fk_playlist_video_playlist FOREIGN KEY(id_playlist) REFERENCES youtube.PLAYLIST(id_playlist)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_playlist_video_video FOREIGN KEY(id_video) REFERENCES youtube.VIDEO(id_video)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.COMMENT(
id_comment INT NOT NULL AUTO_INCREMENT,
comment TEXT NOT NULL,
date_comment DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
id_user INT NOT NULL,
id_video INT NOT NULL,
CONSTRAINT pk_comment PRIMARY KEY(id_comment),
CONSTRAINT fk_comment_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_comment_video FOREIGN KEY(id_video) REFERENCES youtube.VIDEO(id_video)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS youtube.REACTION_COMMENT(
id_user INT NOT NULL,
id_comment INT NOT NULL,
reaction ENUM('LIKE', 'DISLIKE') NOT NULL,
date_reaction_comment DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_reaction_comment PRIMARY KEY(id_user, id_comment),
CONSTRAINT fk_reaction_comment_user FOREIGN KEY(id_user) REFERENCES youtube.USER(id_user)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_reaction_comment_comment FOREIGN KEY(id_comment) REFERENCES youtube.COMMENT(id_comment)
ON DELETE CASCADE ON UPDATE CASCADE);