CREATE SCHEMA IF NOT EXISTS pizzeria;
USE pizzeria;

CREATE TABLE IF NOT EXISTS pizzeria.PROVINCE(
id_province INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
CONSTRAINT pk_province PRIMARY KEY(id_province));

CREATE TABLE IF NOT EXISTS pizzeria.TOWN(
id_town INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
id_province INT NOT NULL,
CONSTRAINT pk_town PRIMARY KEY(id_town),
CONSTRAINT fk_town_province FOREIGN KEY (id_province) REFERENCES pizzeria.PROVINCE(id_province)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.ADDRESS(
id_address INT NOT NULL AUTO_INCREMENT,
street VARCHAR(45) NOT NULL,
number VARCHAR(45) NOT NULL,
floor VARCHAR(45) NULL,
door VARCHAR(45) NULL,
city VARCHAR(45) NOT NULL,
zip_code VARCHAR(45) NULL,
country VARCHAR(45) NOT NULL,
id_town INT NOT NULL, 
CONSTRAINT pk_address PRIMARY KEY(id_address),
CONSTRAINT fk_address_town FOREIGN KEY (id_town) REFERENCES pizzeria.TOWN(id_town)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.CLIENT(
id_client INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
surname VARCHAR(45) NULL,
phone_number VARCHAR(45) NOT NULL,
id_address INT NOT NULL,
CONSTRAINT pk_client PRIMARY KEY(id_client),
CONSTRAINT fk_client_address FOREIGN KEY (id_address) REFERENCES pizzeria.ADDRESS(id_address)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.STORE(
id_store INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL, 
id_address INT NOT NULL,
CONSTRAINT pk_store PRIMARY KEY(id_store),
CONSTRAINT fk_store_address FOREIGN KEY (id_address) REFERENCES pizzeria.ADDRESS(id_address)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.EMPLOYEE(
id_employee INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
surname VARCHAR(45) NOT NULL,
nif VARCHAR(45) NOT NULL,
phone_number VARCHAR(45) NOT NULL,
role ENUM('COOK', 'DELIVERY_DRIVER'),
id_store INT NOT NULL,
id_address INT NOT NULL,
CONSTRAINT pk_employee PRIMARY KEY(id_employee),
CONSTRAINT fk_employee_store FOREIGN KEY (id_store) REFERENCES pizzeria.STORE(id_store)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_employee_address FOREIGN KEY (id_address) REFERENCES pizzeria.ADDRESS(id_address)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.CATEGORY(
id_category INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
CONSTRAINT pk_category PRIMARY KEY(id_category));

CREATE TABLE IF NOT EXISTS pizzeria.PRODUCT(
id_product INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
description TEXT NOT NULL,
image VARCHAR(255) NULL, 
price DECIMAL(6,2) NOT NULL,
type_product ENUM('BURGUER', 'PIZZA', 'DRINK') NOT NULL,
CONSTRAINT pk_product PRIMARY KEY(id_product));

CREATE TABLE IF NOT EXISTS pizzeria.IS_PIZZA(
id_ispizza INT NOT NULL,
id_product INT NOT NULL,
id_category INT NOT NULL,
CONSTRAINT pk_ispizza PRIMARY KEY(id_ispizza),
CONSTRAINT fk_ispizza_product FOREIGN KEY (id_product) REFERENCES pizzeria.PRODUCT(id_product)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_ispizza_category FOREIGN KEY (id_category) REFERENCES pizzeria.CATEGORY(id_category)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.ORDER(
id_order iNT NOT NULL AUTO_INCREMENT,
date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
order_type ENUM('DELIVERY', 'PICKUP') NOT NULL,
total_price DECIMAL(6,2) NOT NULL,
id_client INT NOT NULL,
id_store INT NOT NULL, 
id_delivery_driver INT NULL,
delivery_time DATETIME NULL,
CONSTRAINT pk_order PRIMARY KEY(id_order),
CONSTRAINT fk_order_client FOREIGN KEY (id_client) REFERENCES pizzeria.CLIENT(id_client)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_order_store FOREIGN KEY (id_store) REFERENCES pizzeria.STORE(id_store)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_order_delivery_driver FOREIGN KEY (id_delivery_driver) REFERENCES pizzeria.EMPLOYEE(id_employee)
ON DELETE SET NULL ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS pizzeria.ORDER_PRODUCT(
id_order INT NOT NULL,
id_product INT NOT NULL,
quantity INT NOT NULL DEFAULT 1,
CONSTRAINT pk_order_product PRIMARY KEY(id_order, id_product),
CONSTRAINT fk_order_product_order FOREIGN KEY (id_order) REFERENCES pizzeria.ORDER(id_order)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_order_product_product FOREIGN KEY (id_product) REFERENCES pizzeria.PRODUCT(id_product)
ON DELETE RESTRICT ON UPDATE CASCADE);